### ISSUE TITLE
Unable to update to 2.5.0

### ISSUE THREAD

**Issue by thiphariel** [DH3ALEJANDRO/custom-work-for-brackets#3]
Hi !

First, thanks for your plugin, it's really useful.

Next, I got a small issue after installing it. It was on 2.0.0 and show me the update button, but I was unable to click it (disabled button)

I just delete and reinstall the plugin and now it shows me v2.5.0.

If you can take a look :-) (Sorry but I can't provide more informations :/)

**Comment by DH3ALEJANDRO** [comment]
may be a problem with your brackets application, I have now updated the plugin to 2.5.0, how many times has this happened?

**Comment by thco** [comment]
I can't tell you anymore, cause I'm on 2.5.0 too. But it's a small issue, maybe I'm alone with this but I wanna report that just in case.
If you were enable to update without problem, it's surely Brackets related then

**Comment by maxgrass** [comment]
Same for me, dull green button "cannot use with this version of brackets". Remove and fresh install helps, but it's strange 😮

**Comment by thco** [comment]
Still can't upgrade to 3.0.0 from 2.5.0 too... The update button is disable :/

**Comment by DH3ALEJANDRO** [comment]
I'm trying to stabilize the update. it is advisable to remove the extension and reinstall.

**Comment by maxgrass** [comment]
works. confirmed.
