### ISSUE TITLE
Compatibility problem with a minimap mod...

### ISSUE THREAD

**Issue by sapioit** [DH3ALEJANDRO/custom-work-for-brackets#99]
I use a minimap mod, so the button which lists all tabs is hidden behind the minimap. Could you, please, have an option to move the tabs list to the left of the tabs' list?

**Comment by sapioit** [comment]
![screenshot 132](https://user-images.githubusercontent.com/3173159/30116481-542f2334-9326-11e7-8373-184b6b88f2ca.png)
![screenshot 133](https://user-images.githubusercontent.com/3173159/30116489-572e38c2-9326-11e7-93a7-004d452460c0.png)

**Comment by DH3ALEJANDRO** [comment]
*fixed, please update the Custom Work*

**Comment by sapioit** [comment]
Did you change the location of the repo? I cannot see any change in the code on this repo, and neither can I see any new update. And after trying to re-install the version in this repo and let it update to the latest version, I still cannot find the option to change the dropdown to the left of the bar.

**Comment by DH3ALEJANDRO** [comment]
sorry for the delay, it was an upload error but it is already active.

**Comment by DH3ALEJANDRO** [comment]
please the name of the extension?

**Comment by sapioit** [comment]
The name is just **"[`Minimap`](https://github.com/zorgzerg/brackets-minimap)"**. Link: https://github.com/zorgzerg/brackets-minimap
